### ISSUE TITLE
Downloaded foundry.zip doesn't seem big enough. Check the zip file and URL were correct.

### ISSUE THREAD

**Issue by brandonrhymer** [mikehdt/aws-foundry-ssl#1]
sudo cat /tmp/foundry-setup.log | less

```
+++ stat -c%s ./foundry.zip
++ filesize=218246537
++ echo 'File size of foundry.zip is 218246537 bytes.'
File size of foundry.zip is 218246537 bytes.
++ ((  218246537 > 100000000  ))
++ echo 'File size seems about right! Proceeding...'
File size seems about right! Proceeding...
++ break
++ [[ filesize < rough_filesize ]]
++ echo 'Error: Downloaded foundry.zip doesn'\''t seem big enough. Check the zip file and URL were correct.'
Error: Downloaded foundry.zip doesn't seem big enough. Check the zip file and URL were correct.
++ exit 1
```

Cloud watch error is:
FoundryServer | CREATE_FAILED | Received FAILURE signal with UniqueId i-xxxx

I've ran this with several variations to the parameters.

Admittedly, I'm not the least knowledgeable about this. I installed foundry previously on AWS a few years ago, and locked myself out of my old instance. I went throught the steps to wipe all traces of the old instance, but i could have missed something. Please send help.

Update: I ssh'd in and commented out the final filesize check and everything continued after i ran install.sh again. I'm honestly not sure what else needs to be run. Please advise.

**Comment by mikehdt** [comment]
Aha, looks like I'd made a silly mistake when I was tidying things up.

I've just pushed what should be a fix - `[[ filesize < rough_filesize ]]` should have been `(( $filesize < $rough_filesize ))`. When I was reading through the script I realised that if it gets out of the loop above (more than four failed iterations I think?), it could continue on blissfully unaware that the download had failed so I wanted to check once more to be helpful. I imagine it could hit this condition if the link returned HTML instead of the ZIP eg. if the server is 404 or 500'ing or similar.

The comparison might also work with `[[` brackets and it's probably the lack of `$` that upset it, but I'm going to go with the pattern of what's working from the lines above. Supposedly `[`, `[[`, `(` and `((` are subtly different in ways that I won't claim to understand, heh.

Give it a whirl and let me know if it fixes things for you.
