### ISSUE TITLE
dynamic_dns.sh uses deprecated mechanism to find public_ip

### ISSUE THREAD

**Issue by dougtreder** [mikehdt/aws-foundry-ssl#4]
At least for my EC2 host (after cloud formation finished),  using openDNS to find my public ip doesn't work:

dig +short myip.opendns.com @resolver1.opendns.com

returns nothing.  However, using cloud flare does:

dig +short txt ch whoami.cloudflare @1.0.0.1

so I was able to get /aws-foundry-ssl/setup/aws/dynamic_dns.sh to work by getting the public_ip like this:

# Retrieve public IP
public_ip="$(dig +short txt ch whoami.cloudflare @1.0.0.1)"
strip="${public_ip%\"}"
public_ip="${strip#\"}"

**Comment by mikehdt** [comment]
Interesting, I'll try that out. I also have to update that code to deal with IPv6 which is a whole journey of its own.

I'm also suspicious of the `systemd` timer not firing to retrieve a (likely) new IP when the instance is stopped / restarted, maybe that might be related to this call being a bit unreliable? Will need to check. Thanks.

**Comment by mikehdt** [comment]
I've been playing around with this a bit, and I'm using something similar to
```
ec2_ipv4="$(dig -4 +short txt ch whoami.cloudflare @1.0.0.1 | tr -d '"')"
ec2_ipv6="$(dig -6 +short txt ch whoami.cloudflare @2606:4700:4700::1001 | tr -d '"')"
```
Which at least gets both (although you do have to wait for a timeout if eg. your instance doesn't have IPv6 or soon, IPv4). It's easy to upsert both recordsets from there.

I've found the timers are a bit weird though, so my plan is to figure out what timers activate / or not when an EC2 boots or is restarted, make sure I can get the right ones set up and then rely on this script to set the IPv4/IPv6 addresses. I'll then remove IPv4 RS details from the CloudFormation script, as the upsert behaviour should suffice.

It's... quite a journey 😅

**Comment by mikehdt** [comment]
Okay, I _think_ it's mostly working now. It's a little more fraught in the sense that when you don't use CF to add the IPv4 address to the Route 53 Recordset it starts to rely on the upsert working _before_ Certbot jumps in (otherwise it can't find the domain, and fails). So you're at the whims of things happening in the order you _hope_. Bumped up the start time on certbot to try and give the Recordset enough time, and also fixed some issues with timers more generally. `systemd` is very powerful, but super confusing!

At the least, I've tested restarting the instance, stopping and starting the instance (which issues a new IPv4 address), and deploying from scratch. The script now correctly identifies and updates the recordsets for both `A` and `AAAA` entries. I've still got a few improvements to make, but it should do what it's supposed to now. Thanks for putting me onto what wasn't behaving properly, as it should be a better solution now.

If you try it out, let me know how it goes.

**Comment by mikehdt** [comment]
Going to close this for now; If anything comes up, please feel free to reopen or make a new issue and I'll see what I can do. Thanks!
